# Generated by Django 3.2.6 on 2022-08-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20220821_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ads_images/'),
        ),
    ]
