# Generated by Django 3.2.6 on 2022-08-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_advertisement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('-created_at',), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
